### ISSUE TITLE
describe the funnel?

### ISSUE THREAD

**Issue by cwren-usds** [usds/medicaid-renewals-playbook#3]
I might not have found it yet, but there are lots of references to the funnel but so far, no description of it. 

Are we assuming it is a familiar enough concept? or is this a TODO

**Comment by MaxMazzocchiUSDS** [comment]
The funnel is described and linked here: https://github.com/usds/medicaid-renewals-playbook/blob/2a5939b7b0fa45f86ec807a59c8629ee4e4ccc6e/README.md?plain=1#L86

Feel free to link to that Mural wherever you see funnel referenced without context!
